spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payments
    username: root
    password: Amit@1995
    driver-class-name: com.mysql.cj.jdbc.Driver

  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name:  PAYMENT-SERVICE
     
server:
  port: 5252
  
 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true  
      
    
       