spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: root
    password: Amit@1995
    driver-class-name: com.mysql.cj.jdbc.Driver

  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name:  ORDER-SERVICE
     
server:
  port: 5151
  

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true  
              